### PR TITLE
V4 development - Umbrella-Near Harad faith and early day primitive faith Version 2 (don't worry about it) 

### PR DESCRIPTION
**Pull request by Remerod**
# Introduction
Pull Request about creating 2 new faiths in Near Harad, issue has been discussed and approved on Discord (More info to come)

# Development
- [x] Adding 2 faiths for Near Harad, called **Legends of Harwan** `faith_legends_of_harwan` and **Teachings of Tîrael** `faith_teachings_of_the_tirael`. Making them playable with proper localization's.

X (scraping this for now) Perhaps adding a synchronizing tenet or something similar to the faiths in near harad
- [x] fixing Stats to Yusraa (small nerf)
<details>
<summary>Click to expand</summary>

image

image

image

image

</details>

more coming soon

# Testing
**To do:**

To use/pick this branch go to github desktop and choose Pull Request, and then choose... this one 

<details>
<summary>Click to expand</summary>

image

</details>

- [x] **1.** Review the **Legends of Harwan** `faith_legends_of_harwan` and **Teachings of Tîrael** `faith_teachings_of_the_tirael` faith localizations, tenets, doctrine's and more to see that it fits the region and is balanced well.

 - [x] **2.** Test the character/ruler Yusraa, see if her new Base Stats are currently working
 
 Then but yourself into the reviewed section on the bottom of the Page
 
**How to:**
To check **1.** go into the game and click on harad faiths, click on the **Other Faiths** button on a Near Harad faith to check the 2 new faiths, review it and write a detailed review on this pull issue on whatever it's good or need tweaking and if good then check the checkbox under **To Do** that's it finished. 

To check **2.** go to the character that rules Zakakha in Near Harad/Perzersan and hover over her stats to see her base stats, leave a comment here detailing your findings, and if good then check the checkbox under **To Do** that's it finished.

### CODE REVIEW

**Comment by savagesach** [comment]
image
I think the Legends of Harwan religion needs different localization as the current one seems too generic for me to understand what the religion represents. Apart from that though, the tenets make sense
image
image
I think the Teachings of Tirtael faith needs more virtues and sins, also the faith needs different god names, because I'm pretty sure they should not be worshipping khaz--gramaze. Apart from that, the faith is good.
image
The character's stats are far more normal now. This is fixed.

**Comment by VectorMaximus** [comment]
> I think the Legends of Harwan religion needs different localization as the current one seems too generic for me to understand what the religion represents. Apart from that though, the tenets make sense

The entire point of the faith and it localization is that its meant to be a large umbrella that does not correspond to any one particular theology or worship, instead encompassing many different creeds in northern Harad that would be too small and insignificant to otherwise represent. I do think it should start as unreformed.

**Comment by savagesach** [comment]
okay that makes more sense, I don't understand why all the gods are khaz-gramaze for the religion though if it's supposed to be an umbrella faith

**Comment by Remerod** [comment]
jupp will fix god localizations

**Comment by savagesach** [comment]
image
image
two things, first the teachings of tirtael faith now has no tenets. and second, I get that the faith is supposed to be based on the moon, but "glory to Moon" sounds silly imo

**Comment by savagesach** [comment]
the god names do work though for both religions

**Comment by savagesach** [comment]
After testing, the issues have been resolved and faiths now work as intended.

**Pull request merged**
